package com.demo.Entity.Cart;
import com.demo.Entity.User;

import jakarta.persistence.*; 
import lombok.*; 

@Entity                 //Marks the class as a JPA entity, meaning it will be mapped to a database table
@Table(name = "carts") //Specifies the table name in the database, if it's different from the class name (optional)
@Getter                 //Automatically generates getter methods for all fields
@Setter                 //Automatically generates setter methods for all fields
@NoArgsConstructor      //Generates a no-argument constructor (required for frameworks like JPA and Hibernate)
@AllArgsConstructor     //Generates a constructor with arguments for all fields (useful for object creation)
@Builder                //Enables the builder pattern for constructing instances of the class in a more readable way
public class Cart 
{
    @Id //Marks this field as the primary key in the database
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Automatically generates unique values for the primary key (usually for auto-incremented IDs)
    @Column(name = "cid")                               //Specifies the column name in the database
    private Long cid;                                   //Unique identifier for the cart, typically auto-generated by the database

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)    //Defines a many-to-one relationship with User
    @JoinColumn(name = "uid", nullable = false)                         //Specifies the foreign key column to join on
    private User uid;                                                   //The order associated with this user record
}