package com.demo.DTO;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter             //Generates getters for all fields
@NoArgsConstructor  //Generates a no-argument constructor
@AllArgsConstructor //Generates a constructor with all arguments
@Builder            //Generates a builder pattern for creating instances
public class OrderPaymentDTO 
{
    //Unique identifier for the payment, order, typically auto-generated by the database
    //The ID of the order in the payment
    //The ID of the payment where the order is stored
    private Long poid, oid, pid;
}